[tool.isort]
profile = "black"
multi_line_output = 3
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY',  'FIRSTPARTY', 'LOCALFOLDER']
known_first_party = ["wheeljax"]

[tool.black]
line-length = 88
target_version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
| dist
| data
)/
'''